# copy from https://github.com/zhaozg/lua-openssl/
# thank you zhaozg

language: cpp

os:
  - linux
#  - osx

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
#    - LUA=lua5.2
#    - LUA=lua5.3
#    - LUA=luajit

#branches:
#  only:
#    - master

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - bash .travis/setup_lua.sh

install: 
  - sudo apt-get install -qq g++-4.8
  - sudo rm $(which g++)
  - sudo ln -s $(which g++-4.8) $(which g++)
  - sudo luarocks make lua-brotli-1.0-1.rockspec

script:
#  - cd test
#  - curl https://raw.githubusercontent.com/bluebird75/luaunit/master/luaunit.lua > luaunit.lua
#  - lua test.lua
  - echo ok

notifications:
  email:
    on_success: change
    on_failure: always
