# copy from https://github.com/zhaozg/lua-openssl/
# thank you zhaozg

language: cpp

os:
  - linux
  - osx

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit

#branches:
#  only:
#    - master

before_install:
  - bash ci-scripts/setup_linux_gcc.sh
  - bash ci-scripts/setup_lua.sh

install: 
  - sudo luarocks make lua-brotli-1.0-1.rockspec

script:
  - cd test
  - lua test.lua

notifications:
  email:
    on_success: change
    on_failure: always
