version: 1.0-{build}
configuration: Release
platform: x86
clone_depth: 2
clone_folder: c:\lua-brotli
install:
- '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86'
- c:\lua-brotli\ci-scripts\install_luarocks.bat
build_script:
- cd c:\lua-brotli
- luarocks make lua-brotli-1.0-1.rockspec
test_script:
- cd c:\lua-brotli\test
- lua5.1 test.lua
artifacts:
- path: brotli.dll
